import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Этот файл генерируется: python scripts/docs/gen.py
// Правь scripts/docs/api/*.py, а не его.
const sidebars: SidebarsConfig = {
  docs: [
    {type: 'doc', id: 'intro', label: 'Что это'},
    {type: 'doc', id: 'install', label: 'Установка'},
    {type: 'doc', id: 'plugins', label: 'Структура плагина'},
    {
      type: 'category',
      label: 'Справочник API',
      collapsed: false,
      link: {type: 'doc', id: 'api/index'},
      items: [
        {type: 'category', label: 'hook', collapsed: true, link: {type: 'doc', id: 'api/hook/index'}, items: [
          {type: 'category', label: 'Пространство имён', collapsed: true, items: [
            {type: 'doc', id: 'api/hook/add', label: 'hook.add'},
            {type: 'doc', id: 'api/hook/remove', label: 'hook.remove'},
            {type: 'doc', id: 'api/hook/run', label: 'hook.run'},
            {type: 'doc', id: 'api/hook/list', label: 'hook.list'},
          ]},
          {type: 'category', label: 'Подключение', collapsed: true, items: [
            {type: 'doc', id: 'api/hook/client_connect', label: 'client_connect'},
            {type: 'doc', id: 'api/hook/client_disconnect', label: 'client_disconnect'},
            {type: 'doc', id: 'api/hook/player_authorized', label: 'player_authorized'},
            {type: 'doc', id: 'api/hook/player_ready', label: 'player_ready'},
            {type: 'doc', id: 'api/hook/player_chat', label: 'player_chat'},
            {type: 'doc', id: 'api/hook/menu_select', label: 'menu_select'},
          ]},
          {type: 'category', label: 'Жизнь сервера', collapsed: true, items: [
            {type: 'doc', id: 'api/hook/map_change', label: 'map_change'},
            {type: 'doc', id: 'api/hook/plugin_unload', label: 'plugin_unload'},
          ]},
          {type: 'category', label: 'Геймплей', collapsed: true, items: [
            {type: 'doc', id: 'api/hook/player_spawn', label: 'player_spawn'},
            {type: 'doc', id: 'api/hook/player_hurt', label: 'player_hurt'},
            {type: 'doc', id: 'api/hook/player_hurt_post', label: 'player_hurt_post'},
            {type: 'doc', id: 'api/hook/player_death', label: 'player_death'},
            {type: 'doc', id: 'api/hook/player_team_change', label: 'player_team_change'},
            {type: 'doc', id: 'api/hook/weapon_fire', label: 'weapon_fire'},
          ]},
          {type: 'category', label: 'Раунд и бомба', collapsed: true, items: [
            {type: 'doc', id: 'api/hook/round_start', label: 'round_start'},
            {type: 'doc', id: 'api/hook/round_end', label: 'round_end'},
            {type: 'doc', id: 'api/hook/round_freeze_end', label: 'round_freeze_end'},
            {type: 'doc', id: 'api/hook/bomb_planted', label: 'bomb_planted'},
            {type: 'doc', id: 'api/hook/bomb_defused', label: 'bomb_defused'},
            {type: 'doc', id: 'api/hook/bomb_exploded', label: 'bomb_exploded'},
          ]},
        ]},
        {type: 'category', label: 'cmd', collapsed: true, link: {type: 'doc', id: 'api/cmd/index'}, items: [
          {type: 'doc', id: 'api/cmd/add', label: 'cmd.add'},
          {type: 'doc', id: 'api/cmd/remove', label: 'cmd.remove'},
          {type: 'doc', id: 'api/cmd/list', label: 'cmd.list'},
        ]},
        {type: 'category', label: 'players', collapsed: true, link: {type: 'doc', id: 'api/players/index'}, items: [
          {type: 'category', label: 'Пространство имён', collapsed: true, items: [
            {type: 'doc', id: 'api/players/get', label: 'players.get'},
            {type: 'doc', id: 'api/players/list', label: 'players.list'},
            {type: 'doc', id: 'api/players/find', label: 'players.find'},
            {type: 'doc', id: 'api/players/broadcast', label: 'players.broadcast'},
            {type: 'doc', id: 'api/players/method', label: 'players.method'},
          ]},
          {type: 'category', label: 'Идентификация', collapsed: true, items: [
            {type: 'doc', id: 'api/players/id', label: 'p.id'},
            {type: 'doc', id: 'api/players/name', label: 'p:name'},
            {type: 'doc', id: 'api/players/ip', label: 'p:ip'},
            {type: 'doc', id: 'api/players/steamid', label: 'p:steamid'},
            {type: 'doc', id: 'api/players/userid', label: 'p:userid'},
            {type: 'doc', id: 'api/players/info', label: 'p:info'},
            {type: 'doc', id: 'api/players/connected', label: 'p:connected'},
            {type: 'doc', id: 'api/players/is_bot', label: 'p:is_bot'},
            {type: 'doc', id: 'api/players/is_hltv', label: 'p:is_hltv'},
          ]},
          {type: 'category', label: 'Состояние', collapsed: true, items: [
            {type: 'doc', id: 'api/players/health', label: 'p:health'},
            {type: 'doc', id: 'api/players/armor', label: 'p:armor'},
            {type: 'doc', id: 'api/players/frags', label: 'p:frags'},
            {type: 'doc', id: 'api/players/gravity', label: 'p:gravity'},
            {type: 'doc', id: 'api/players/maxspeed', label: 'p:maxspeed'},
            {type: 'doc', id: 'api/players/origin', label: 'p:origin'},
            {type: 'doc', id: 'api/players/angles', label: 'p:angles'},
            {type: 'doc', id: 'api/players/velocity', label: 'p:velocity'},
            {type: 'doc', id: 'api/players/aim', label: 'p:aim'},
            {type: 'doc', id: 'api/players/alive', label: 'p:alive'},
            {type: 'doc', id: 'api/players/on_ground', label: 'p:on_ground'},
            {type: 'doc', id: 'api/players/ducking', label: 'p:ducking'},
            {type: 'doc', id: 'api/players/freeze', label: 'p:freeze'},
            {type: 'doc', id: 'api/players/godmode', label: 'p:godmode'},
            {type: 'doc', id: 'api/players/noclip', label: 'p:noclip'},
            {type: 'doc', id: 'api/players/trace', label: 'p:trace'},
          ]},
          {type: 'category', label: 'CS-состояние', collapsed: true, items: [
            {type: 'doc', id: 'api/players/team', label: 'p:team'},
            {type: 'doc', id: 'api/players/spawn', label: 'p:spawn'},
            {type: 'doc', id: 'api/players/money', label: 'p:money'},
            {type: 'doc', id: 'api/players/deaths', label: 'p:deaths'},
            {type: 'doc', id: 'api/players/give', label: 'p:give'},
            {type: 'doc', id: 'api/players/strip', label: 'p:strip'},
            {type: 'doc', id: 'api/players/weapon', label: 'p:weapon'},
            {type: 'doc', id: 'api/players/weapons', label: 'p:weapons'},
            {type: 'doc', id: 'api/players/ammo', label: 'p:ammo'},
            {type: 'doc', id: 'api/players/clip', label: 'p:clip'},
            {type: 'doc', id: 'api/players/drop', label: 'p:drop'},
          ]},
          {type: 'category', label: 'Сообщения', collapsed: true, items: [
            {type: 'doc', id: 'api/players/chat', label: 'p:chat'},
            {type: 'doc', id: 'api/players/console', label: 'p:console'},
            {type: 'doc', id: 'api/players/center', label: 'p:center'},
            {type: 'doc', id: 'api/players/hud', label: 'p:hud'},
            {type: 'doc', id: 'api/players/dhud', label: 'p:dhud'},
            {type: 'doc', id: 'api/players/motd', label: 'p:motd'},
            {type: 'doc', id: 'api/players/play_sound', label: 'p:play_sound'},
          ]},
          {type: 'category', label: 'Админские действия', collapsed: true, items: [
            {type: 'doc', id: 'api/players/kick', label: 'p:kick'},
            {type: 'doc', id: 'api/players/ban', label: 'p:ban'},
            {type: 'doc', id: 'api/players/slay', label: 'p:slay'},
            {type: 'doc', id: 'api/players/slap', label: 'p:slap'},
            {type: 'doc', id: 'api/players/exec', label: 'p:exec'},
          ]},
          {type: 'category', label: 'Права', collapsed: true, items: [
            {type: 'doc', id: 'api/players/can', label: 'p:can'},
            {type: 'doc', id: 'api/players/groups', label: 'p:groups'},
            {type: 'doc', id: 'api/players/group', label: 'p:group'},
            {type: 'doc', id: 'api/players/weight', label: 'p:weight'},
            {type: 'doc', id: 'api/players/outranks', label: 'p:outranks'},
          ]},
        ]},
        {type: 'category', label: 'timer', collapsed: true, link: {type: 'doc', id: 'api/timer/index'}, items: [
          {type: 'category', label: 'Анонимные', collapsed: true, items: [
            {type: 'doc', id: 'api/timer/after', label: 'timer.after'},
            {type: 'doc', id: 'api/timer/every', label: 'timer.every'},
            {type: 'doc', id: 'api/timer/cancel', label: 'timer.cancel'},
          ]},
          {type: 'category', label: 'Именованные', collapsed: true, items: [
            {type: 'doc', id: 'api/timer/create', label: 'timer.create'},
            {type: 'doc', id: 'api/timer/destroy', label: 'timer.destroy'},
          ]},
        ]},
        {type: 'category', label: 'ents', collapsed: true, link: {type: 'doc', id: 'api/ents/index'}, items: [
          {type: 'category', label: 'Пространство имён', collapsed: true, items: [
            {type: 'doc', id: 'api/ents/create', label: 'ents.create'},
            {type: 'doc', id: 'api/ents/find', label: 'ents.find'},
            {type: 'doc', id: 'api/ents/in_sphere', label: 'ents.in_sphere'},
          ]},
          {type: 'category', label: 'Объект сущности', collapsed: true, items: [
            {type: 'doc', id: 'api/ents/index', label: 'e.index'},
            {type: 'doc', id: 'api/ents/origin', label: 'e:origin'},
            {type: 'doc', id: 'api/ents/angles', label: 'e:angles'},
            {type: 'doc', id: 'api/ents/model', label: 'e:model'},
            {type: 'doc', id: 'api/ents/classname', label: 'e:classname'},
            {type: 'doc', id: 'api/ents/valid', label: 'e:valid'},
            {type: 'doc', id: 'api/ents/spawn', label: 'e:spawn'},
            {type: 'doc', id: 'api/ents/remove', label: 'e:remove'},
            {type: 'doc', id: 'api/ents/keyvalue', label: 'e:keyvalue'},
            {type: 'doc', id: 'api/ents/solid', label: 'e:solid'},
            {type: 'doc', id: 'api/ents/movetype', label: 'e:movetype'},
            {type: 'doc', id: 'api/ents/size', label: 'e:size'},
            {type: 'doc', id: 'api/ents/render', label: 'e:render'},
          ]},
        ]},
        {type: 'category', label: 'res', collapsed: true, link: {type: 'doc', id: 'api/res/index'}, items: [
          {type: 'doc', id: 'api/res/sound', label: 'res.sound'},
          {type: 'doc', id: 'api/res/model', label: 'res.model'},
        ]},
        {type: 'category', label: 'sv', collapsed: true, link: {type: 'doc', id: 'api/sv/index'}, items: [
          {type: 'category', label: 'Сервер', collapsed: true, items: [
            {type: 'doc', id: 'api/sv/time', label: 'sv.time'},
            {type: 'doc', id: 'api/sv/map', label: 'sv.map'},
            {type: 'doc', id: 'api/sv/cmd', label: 'sv.cmd'},
          ]},
          {type: 'category', label: 'Cvar', collapsed: true, items: [
            {type: 'doc', id: 'api/sv/cvar', label: 'sv.cvar'},
            {type: 'doc', id: 'api/sv/cvar_register', label: 'sv.cvar_register'},
            {type: 'doc', id: 'api/sv/int', label: 'c:int'},
            {type: 'doc', id: 'api/sv/float', label: 'c:float'},
            {type: 'doc', id: 'api/sv/str', label: 'c:str'},
            {type: 'doc', id: 'api/sv/set', label: 'c:set'},
            {type: 'doc', id: 'api/sv/name', label: 'c:name'},
          ]},
        ]},
        {type: 'category', label: 'db', collapsed: true, link: {type: 'doc', id: 'api/db/index'}, items: [
          {type: 'category', label: 'Открытие', collapsed: true, items: [
            {type: 'doc', id: 'api/db/open', label: 'db.open'},
          ]},
          {type: 'category', label: 'Объект базы', collapsed: true, items: [
            {type: 'doc', id: 'api/db/exec', label: 'db:exec'},
            {type: 'doc', id: 'api/db/query', label: 'db:query'},
            {type: 'doc', id: 'api/db/first', label: 'db:first'},
            {type: 'doc', id: 'api/db/prepare', label: 'db:prepare'},
            {type: 'doc', id: 'api/db/transaction', label: 'db:transaction'},
            {type: 'doc', id: 'api/db/last_id', label: 'db:last_id'},
            {type: 'doc', id: 'api/db/changes', label: 'db:changes'},
            {type: 'doc', id: 'api/db/path', label: 'db:path'},
            {type: 'doc', id: 'api/db/close', label: 'db:close'},
          ]},
          {type: 'category', label: 'Подготовленное выражение', collapsed: true, items: [
            {type: 'doc', id: 'api/db/stmt_run', label: 'st:run'},
            {type: 'doc', id: 'api/db/stmt_query', label: 'st:query'},
            {type: 'doc', id: 'api/db/stmt_first', label: 'st:first'},
            {type: 'doc', id: 'api/db/stmt_sql', label: 'st:sql'},
            {type: 'doc', id: 'api/db/stmt_close', label: 'st:close'},
          ]},
        ]},
        {type: 'category', label: 'store', collapsed: true, link: {type: 'doc', id: 'api/store/index'}, items: [
          {type: 'category', label: 'store', collapsed: true, items: [
            {type: 'doc', id: 'api/store/open', label: 'store.open'},
            {type: 'doc', id: 'api/store/get', label: 's:get'},
            {type: 'doc', id: 'api/store/set', label: 's:set'},
            {type: 'doc', id: 'api/store/delete', label: 's:delete'},
            {type: 'doc', id: 'api/store/keys', label: 's:keys'},
            {type: 'doc', id: 'api/store/all', label: 's:all'},
            {type: 'doc', id: 'api/store/flush', label: 's:flush'},
            {type: 'doc', id: 'api/store/pending', label: 's:pending'},
          ]},
          {type: 'category', label: 'datafile', collapsed: true, items: [
            {type: 'doc', id: 'api/store/at', label: 'datafile.at'},
            {type: 'doc', id: 'api/store/load', label: 'datafile.load'},
            {type: 'doc', id: 'api/store/save', label: 'datafile.save'},
            {type: 'doc', id: 'api/store/serialize', label: 'datafile.serialize'},
            {type: 'doc', id: 'api/store/dir', label: 'datafile.dir'},
          ]},
        ]},
        {type: 'category', label: 'menu', collapsed: true, link: {type: 'doc', id: 'api/menu/index'}, items: [
          {type: 'doc', id: 'api/menu/new', label: 'menu.new'},
          {type: 'doc', id: 'api/menu/add', label: 'm:add'},
          {type: 'doc', id: 'api/menu/show', label: 'm:show'},
          {type: 'doc', id: 'api/menu/close', label: 'm:close'},
          {type: 'doc', id: 'api/menu/count', label: 'm:count'},
          {type: 'doc', id: 'api/menu/color', label: 'm:color'},
          {type: 'doc', id: 'api/menu/item_color', label: 'm:item_color'},
        ]},
        {type: 'category', label: 'ui', collapsed: true, link: {type: 'doc', id: 'api/ui/index'}, items: [
          {type: 'doc', id: 'api/ui/color', label: 'ui.color'},
        ]},
        {type: 'category', label: 'access', collapsed: true, link: {type: 'doc', id: 'api/access/index'}, items: [
          {type: 'category', label: 'Объявление', collapsed: true, items: [
            {type: 'doc', id: 'api/access/declare', label: 'access.declare'},
            {type: 'doc', id: 'api/access/rule', label: 'access.rule'},
          ]},
          {type: 'category', label: 'Выдача', collapsed: true, items: [
            {type: 'doc', id: 'api/access/grant', label: 'access.grant'},
            {type: 'doc', id: 'api/access/revoke', label: 'access.revoke'},
            {type: 'doc', id: 'api/access/save', label: 'access.save'},
            {type: 'doc', id: 'api/access/reload', label: 'access.reload'},
            {type: 'doc', id: 'api/access/invalidate', label: 'access.invalidate'},
          ]},
          {type: 'category', label: 'Чтение', collapsed: true, items: [
            {type: 'doc', id: 'api/access/can', label: 'access.can'},
            {type: 'doc', id: 'api/access/permissions', label: 'access.permissions'},
            {type: 'doc', id: 'api/access/users', label: 'access.users'},
            {type: 'doc', id: 'api/access/user', label: 'access.user'},
            {type: 'doc', id: 'api/access/all_groups', label: 'access.all_groups'},
            {type: 'doc', id: 'api/access/group', label: 'access.group'},
          ]},
        ]},
        {type: 'category', label: 'plugin', collapsed: true, link: {type: 'doc', id: 'api/plugin/index'}, items: [
          {type: 'doc', id: 'api/plugin/manifest', label: 'plugin{}'},
          {type: 'doc', id: 'api/plugin/id', label: 'plugin.id'},
          {type: 'doc', id: 'api/plugin/dir', label: 'plugin.dir'},
          {type: 'doc', id: 'api/plugin/data_dir', label: 'plugin.data_dir'},
          {type: 'doc', id: 'api/plugin/on_unload', label: 'plugin.on_unload'},
        ]},
        {type: 'category', label: 'export / import', collapsed: true, link: {type: 'doc', id: 'api/exports/index'}, items: [
          {type: 'doc', id: 'api/exports/export', label: 'export'},
          {type: 'doc', id: 'api/exports/import', label: 'import'},
          {type: 'doc', id: 'api/exports/optional', label: 'optional'},
        ]},
        {type: 'doc', id: 'api/all', label: 'Все вызовы'},
        {type: 'doc', id: 'api/console', label: 'Консольные команды'},
      ],
    },
    {type: 'doc', id: 'migration', label: 'Переход с v1 на v2'},
    {type: 'doc', id: 'building', label: 'Сборка модуля'},
  ],
};

export default sidebars;
